### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by zgbkdlm** [Badr-MOUFAD/dcps#1]
Hi,

I am working on a project that needs to integrate your implementation of divide-conquer SMC. However, your repo does not specify a license, and as such no permissions are granted. I am not even allowed to clone your repo, even though github provides the functionality. Could you please add a license? 

Thank you!

**Comment by Badr-MOUFAD** [comment]
Thanks @zgbkdlm for your interest.
I have added a license for the code.
